// Array to store the colors of the buttons.
var buttonColours = ["red", "blue", "green", "yellow"];

// Array to store the game pattern generated by the computer.
var gamePattern = [];

// Array to store the user's clicked pattern.
var userClickedPattern = [];

// Boolean variable to track if the game has started.
var started = false;

// Variable to keep track of the current level.
var level = 0;

// Event listener for keypress on the document. Starts the game if it hasn't started.
$(document).keypress(function() {
  if (!started) {
    // Update the level title.
    $("#level-title").text("Level " + level);
    // Generate the first sequence.
    nextSequence();
    // Set started to true.
    started = true;
  }
});

// Event listener for clicks on the buttons.
$(".btn").click(function() {
  // Get the ID of the clicked button (which corresponds to the color).
  var userChosenColour = $(this).attr("id");
  // Add the clicked color to the user's pattern.
  userClickedPattern.push(userChosenColour);

  // Play the sound associated with the clicked color.
  playSound(userChosenColour);
  // Animate the button press.
  animatePress(userChosenColour);

  // Check the user's answer against the game pattern.
  checkAnswer(userClickedPattern.length - 1);
});

// Function to check the user's answer.
function checkAnswer(currentLevel) {
  // Check if the current color in the user's pattern matches the game pattern.
  if (gamePattern[currentLevel] === userClickedPattern[currentLevel]) {
    // Log success to the console.
    console.log("success");
    // Check if the user has completed the current level.
    if (userClickedPattern.length === gamePattern.length) {
      // Wait for 1 second and then generate the next sequence.
      setTimeout(function() {
        nextSequence();
      }, 1000);
    }
  } else {
    // If the user's answer is wrong:
    // Play the "wrong" sound.
    playSound("wrong");
    // Add the "game-over" class to the body.
    $("body").addClass("game-over");
    // Remove the "game-over" class after 200 milliseconds.
    setTimeout(function() {
      $("body").removeClass("game-over");
    }, 200);

    // Update the level title to indicate game over.
    $("#level-title").text("Game Over, Press Any Key to Restart");

    // Reset the game.
    startOver();
  }
}

// Function to generate the next sequence in the game.
function nextSequence() {
  // Reset the user's clicked pattern for the new level.
  userClickedPattern = [];

  // Increment the level.
  level++;

  // Update the level title.
  $("#level-title").text("Level " + level);

  // Generate a random number between 0 and 3.
  var randomNumber = Math.floor(Math.random() * 4);
  // Choose a random color from the buttonColours array.
  var randomChosenColour = buttonColours[randomNumber];
  // Add the chosen color to the game pattern.
  gamePattern.push(randomChosenColour);

  // Animate the chosen button.
  $("#" + randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);
  // Play the sound associated with the chosen color.
  playSound(randomChosenColour);
}

// Function to play a sound.
function playSound(name) {
  // Create a new Audio object with the specified sound file.
  var audio = new Audio("sounds/" + name + ".mp3");
  // Play the sound.
  audio.play();
}

// Function to animate a button press.
function animatePress(currentColor) {
  // Add the "pressed" class to the button.
  $("#" + currentColor).addClass("pressed");
  // Remove the "pressed" class after 100 milliseconds.
  setTimeout(function() {
    $("#" + currentColor).removeClass("pressed");
  }, 100);
}

// Function to reset the game.
function startOver() {
  // Reset the level, game pattern, and started flag.
  level = 0;
  gamePattern = [];
  started = false;
}